#!/usr/bin/env python
"""
ExperimentsApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
from urllib.parse import quote

from .models import *


class ExperimentsApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def setCustomerExperiment(self, **kwargs):
        r"""[DEPRECATED] Please don&#39;t use this anymore.\n     *       This endpoint is currently disabled and will be removed.

        Args:
            
            country, str: Country code(s). Usage: ?country=DE,US (required)
            
            
            id, str: The id of the user or &#39;me&#39; to get the userId from the login token (required)
            
            
            locale, str: Locale. Usage: ?locale=fr-BE (required)
            
            
        
        Returns: ApiModel\CustomerExperiment\CustomerExperimentCollection
        """

        allParams = ['country', 'id', 'locale']

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method setCustomerExperiment" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/customers/{id}/experiments'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'

        
        if 'country' in params:
            queryParams['country'] = self.apiClient.toPathValue(params['country'])
        
        if 'locale' in params:
            queryParams['locale'] = self.apiClient.toPathValue(params['locale'])
        

        

        
        if 'id' in params:
            replacement = str(self.apiClient.toPathValue(params['id']))
            replacement = quote(replacement)
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        

        

        postData = formParams if formParams else bodyParam

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, r'ApiModel\CustomerExperiment\CustomerExperimentCollection')
        return responseObject
        
        
        
    
    def getCustomersByCampaign(self, **kwargs):
        r"""[DEPRECATED] Please don&#39;t use this anymore.\n     *       This endpoint is currently disabled and will be removed.

        Args:
            
        
        Returns: ApiModel\Customer\CustomerMinified
        """

        allParams = []

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getCustomersByCampaign" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/experiments/{campaign}/customers'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'

        

        

        

        

        

        postData = formParams if formParams else bodyParam

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, r'ApiModel\Customer\CustomerMinified')
        return responseObject
        
        
        
    


