#!/usr/bin/env python
"""
PartnersApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
from urllib.parse import quote

from .models import *


class PartnersApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def postMedibankMember(self, **kwargs):
        r"""Validate if Medibank membership is valid and link to a HelloFresh account

        Args:
            
            email, : Customer&#39;s Hellofresh email (required)
            
            
            medibankEmail, : Customer&#39;s Medibank email (required)
            
            
            medibankPolicyNumber, : Customer&#39;s Medibank policy number (required)
            
            
            country, str: Country code(s). Usage: ?country=DE,US (required)
            
            
            locale, str: Locale. Usage: ?locale=fr-BE (required)
            
            
        
        Returns: 
        """

        allParams = ['email', 'medibankEmail', 'medibankPolicyNumber', 'country', 'locale']

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method postMedibankMember" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/partners/medibank/verifyMember'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'

        
        if 'country' in params:
            queryParams['country'] = self.apiClient.toPathValue(params['country'])
        
        if 'locale' in params:
            queryParams['locale'] = self.apiClient.toPathValue(params['locale'])
        

        

        

        

        
        if 'medibankPolicyNumber' in params:
            bodyParam = params['medibankPolicyNumber']
        

        postData = formParams if formParams else bodyParam

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        
        
    


