#!/usr/bin/env python
"""
PreordersApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
from urllib.parse import quote

from .models import *


class PreordersApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def createPreOrderForBundle(self, **kwargs):
        r"""Create the payload to place an order for a bundle

        Args:
            
            sku, str: Product SKU (required)
            
            
            subscription, int: Subscription ID to get payment and address information from for the new order (required)
            
            
            postcode, str: Postcode to retrieve an available delivery option for the new order (required)
            
            
            id, int: Resource ID (required)
            
            
            country, str: Country code(s). Usage: ?country=DE,US (required)
            
            
        
        Returns: 
        """

        allParams = ['sku', 'subscription', 'postcode', 'id', 'country']

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createPreOrderForBundle" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/customers/{id}/pre-orders/bundle'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'

        
        if 'country' in params:
            queryParams['country'] = self.apiClient.toPathValue(params['country'])
        

        

        
        if 'id' in params:
            replacement = str(self.apiClient.toPathValue(params['id']))
            replacement = quote(replacement)
            resourcePath = resourcePath.replace('{' + 'id' + '}',
                                                replacement)
        

        
        if 'sku' in params:
            formParams['sku'] = params['sku']
        
        if 'subscription' in params:
            formParams['subscription'] = params['subscription']
        
        if 'postcode' in params:
            formParams['postcode'] = params['postcode']
        

        

        postData = formParams if formParams else bodyParam

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        
        
    


