#!/usr/bin/env python
"""
SubscribeApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
from urllib.parse import quote

from .models import *


class SubscribeApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def fireCartAbandonedEvent(self, **kwargs):
        r"""Fire a cart-abandoned event

        Args:
            
            email, str: User email (required)
            
            
            country, str: Country code(s). Usage: ?country=DE,US (required)
            
            
            originMetadata, ApiModel\Newsletter\OriginMetadata: Origin metadata payload (required)
            
            
            locale, str: Locale. Usage: ?locale=fr-BE (required)
            
            
        
        Returns: 
        """

        allParams = ['email', 'country', 'originMetadata', 'locale']

        params = locals()
        for key, val in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method fireCartAbandonedEvent" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/subscribe/cart-abandoned/{email}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'

        
        if 'country' in params:
            queryParams['country'] = self.apiClient.toPathValue(params['country'])
        
        if 'locale' in params:
            queryParams['locale'] = self.apiClient.toPathValue(params['locale'])
        

        

        
        if 'email' in params:
            replacement = str(self.apiClient.toPathValue(params['email']))
            replacement = quote(replacement)
            resourcePath = resourcePath.replace('{' + 'email' + '}',
                                                replacement)
        

        

        
        if 'originMetadata' in params:
            bodyParam = params['originMetadata']
        

        postData = formParams if formParams else bodyParam

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        
        
    


